FROM node:9.11.1-alpine as build

COPY . /opt/ant-news

WORKDIR /opt/ant-news

RUN set -xue; \
        yarn config set registry 'https://registry.npm.taobao.org' && \
        yarn && \
        yarn run build:cli && \
        yarn run build:con

FROM nginx:1.15.0-alpine

COPY --from=build /opt/ant-news/dist/client /opt/ant-news/client
COPY --from=build /opt/ant-news/dist/console /opt/ant-news/console

COPY docker/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 8080

